##############################################################################
#  Copyright Christopher Kormanyos 2023 - 2025.
#  Distributed under the Boost Software License,
#  Version 1.0. (See accompanying file LICENSE_1_0.txt
#  or copy at http://www.boost.org/LICENSE_1_0.txt)

name: real-time-cpp-snippets
on:
  push:
    branches:
      - '**'
  pull_request:
  schedule:
    - cron: '48 23 * * *' # run at 11:48 PM UTC
jobs:
  host-snippets-all:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        chapter: [ appendix0a, chapter01, chapter03, chapter04, chapter05, chapter07, chapter08, chapter09, chapter12, chapter16, chapter17 ]
        compiler: [ g++, clang++ ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: host-snippets-all
        run: |
          cd ${{ matrix.chapter }}
          ./${{ matrix.chapter }}.sh ${{ matrix.compiler }} c++23
        working-directory: ./code_snippets
  host-snippets-chapter06:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        chapter: [ chapter06 ]
        compiler: [ g++, clang++ ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: clone-submods-bootstrap-headers-boost-develop
        run: |
          git clone -b develop --depth 1 https://github.com/boostorg/boost.git ../boost-root
          cd ../boost-root
          git submodule update --init tools
          git submodule update --init libs/config
          git submodule update --init libs/core
          git submodule update --init libs/detail
          git submodule update --init libs/iterator
          git submodule update --init libs/mp11
          git submodule update --init libs/mpl
          git submodule update --init libs/preprocessor
          git submodule update --init libs/static_assert
          git submodule update --init libs/type_traits
          ./bootstrap.sh
          ./b2 headers
      - name: host-snippets-chapter06
        run: |
          cd ${{ matrix.chapter }}
          ./${{ matrix.chapter }}.sh ${{ matrix.compiler }} c++20
        working-directory: ./code_snippets
  host-snippets-chapter10:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        chapter: [ chapter10 ]
        compiler: [ g++, clang++ ]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: '0'
      - name: clone-submods-bootstrap-headers-boost-develop
        run: |
          git clone -b develop --depth 1 https://github.com/boostorg/boost.git ../boost-root
          cd ../boost-root
          git submodule update --init tools
          git submodule update --init libs/config
          git submodule update --init libs/multiprecision
          ./bootstrap.sh
          ./b2 headers
      - name: update-tools
        run: sudo apt install libgmp-dev
      - name: host-snippets-chapter10
        run: |
          cd ${{ matrix.chapter }}
          ./${{ matrix.chapter }}.sh ${{ matrix.compiler }} c++20
        working-directory: ./code_snippets
